package appB.idl;


/**
* idl/BServiceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/main/java/appB/idl/BService.idl
* Thursday, March 13, 2025 1:59:56 PM TRT
*/

public interface BServiceOperations 
{
  String getData (String request);
} // interface BServiceOperations
