package appB.idl;

/**
* idl/BServiceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/main/java/appB/idl/BService.idl
* Thursday, March 13, 2025 1:59:56 PM TRT
*/

public final class BServiceHolder implements org.omg.CORBA.portable.Streamable
{
  public appB.idl.BService value = null;

  public BServiceHolder ()
  {
  }

  public BServiceHolder (appB.idl.BService initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = appB.idl.BServiceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    appB.idl.BServiceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return appB.idl.BServiceHelper.type ();
  }

}
