package appB.idl;


/**
* idl/BService.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/main/java/appB/idl/BService.idl
* Thursday, March 13, 2025 1:59:56 PM TRT
*/

public interface BService extends BServiceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface BService
