package appA.idl;


/**
* idl/_AServiceStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/main/java/appA/idl/AService.idl
* Thursday, March 13, 2025 1:26:02 PM TRT
*/

public class _AServiceStub extends org.omg.CORBA.portable.ObjectImpl implements appA.idl.AService
{

  public String processRequest (String request)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("processRequest", true);
                $out.write_string (request);
                $in = _invoke ($out);
                String $result = $in.read_string ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return processRequest (request        );
            } finally {
                _releaseReply ($in);
            }
  } // processRequest

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:idl/AService:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  @SuppressWarnings("restriction")
  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     com.sun.corba.se.impl.orbutil.IORCheckImpl.check(str, "idl._AServiceStub");
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _AServiceStub
