package appA.idl;


/**
* idl/AService.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/main/java/appA/idl/AService.idl
* Thursday, March 13, 2025 1:26:02 PM TRT
*/

public interface AService extends AServiceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface AService
