package appA.idl;


/**
* idl/AServiceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/main/java/appA/idl/AService.idl
* Thursday, March 13, 2025 1:26:02 PM TRT
*/

public interface AServiceOperations 
{
  String processRequest (String request);
} // interface AServiceOperations
